# Generated by Django 4.1.7 on 2023-03-07 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='machinedirectory',
            options={'verbose_name': 'Справочник агрегатов', 'verbose_name_plural': 'Справочники агрегатов'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'ТО', 'verbose_name_plural': 'ТО'},
        ),
        migrations.AlterModelOptions(
            name='reclamation',
            options={'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='repairdirectory',
            options={'verbose_name': 'Справочник по обслуживанию', 'verbose_name_plural': 'Справочники по обслуживанию'},
        ),
        migrations.AddField(
            model_name='reclamation',
            name='downtime',
            field=models.PositiveIntegerField(default=0, verbose_name='Время простоя техники'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='consignee',
            field=models.TextField(verbose_name='Грузополучатель (конечный потребитель)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='delivery_address',
            field=models.TextField(verbose_name='Адрес поставки (эксплуатации)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='dispatch_date',
            field=models.DateField(verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='drive_axles', to='service.machinedirectory', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_number',
            field=models.CharField(max_length=255, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='engines', to='service.machinedirectory', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_number',
            field=models.CharField(max_length=255, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='equipment',
            field=models.TextField(verbose_name='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='factory_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='machine_models', to='service.machinedirectory', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steered_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='steered_axles', to='service.machinedirectory', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steered_axle_number',
            field=models.CharField(max_length=255, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='supply_contract_number_date',
            field=models.CharField(max_length=255, verbose_name='Договор поставки №, дата'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transmissions', to='service.machinedirectory', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_number',
            field=models.CharField(max_length=255, verbose_name='Зав. № трансмиссии'),
        ),
        migrations.AlterField(
            model_name='machinedirectory',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='machinedirectory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='machinedirectory',
            name='type',
            field=models.CharField(choices=[('MCN', 'Модель техники'), ('ENG', 'Модель двигателя'), ('TRM', 'Модель трансмиссии'), ('DRA', 'Модель ведущего моста'), ('STA', 'Модель управляемого моста'), ('NDT', 'Нет данных')], default='NDT', max_length=3, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='service.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='holders', to='service.repairdirectory', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='operating_time',
            field=models.PositiveIntegerField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='types', to='service.repairdirectory', verbose_name='Вид ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_date',
            field=models.DateField(verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_number',
            field=models.CharField(max_length=255, verbose_name='№ заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='description',
            field=models.TextField(verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='service.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='operating_time',
            field=models.PositiveIntegerField(verbose_name='Наработка м/час'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='recovery_date',
            field=models.DateField(verbose_name='Дата восстановления'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='rejection_date',
            field=models.DateField(verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='repair_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='methods', to='service.repairdirectory', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='spare_parts',
            field=models.TextField(verbose_name='Используемые запасные части'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='units', to='service.repairdirectory', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='repairdirectory',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='repairdirectory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='repairdirectory',
            name='type',
            field=models.CharField(choices=[('MNT', 'Вид ТО'), ('RPT', 'Способ восстановления'), ('UNT', 'Узел отказа'), ('MTH', 'Организация, проводившая ТО'), ('NDT', 'Нет данных')], default='NDT', max_length=3, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('MNU', 'Конечный клиент'), ('SVC', 'Сервисная организация'), ('MFR', 'Представитель производителя')], default='MNU', max_length=3, verbose_name='Тип пользователя'),
        ),
        migrations.CreateModel(
            name='ServiceCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сервисной организации')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт в системе')),
            ],
            options={
                'verbose_name': 'Карточка сервисной организации',
                'verbose_name_plural': 'Карточки сервисных организаций',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации-клиента')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт в системе')),
            ],
            options={
                'verbose_name': 'Карточка клиента',
                'verbose_name_plural': 'Карточки клиентов',
            },
        ),
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='machines_in_use', to='service.clientprofile', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='maintain_units', to='service.servicecompanyprofile', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='maintenances', to='service.servicecompanyprofile', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reclamations', to='service.servicecompanyprofile', verbose_name='Сервисная компания'),
        ),
    ]
