# Generated by Django 4.1.7 on 2023-03-28 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_machine_client_alter_machine_service_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт в системе'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machines_in_use', to='service.clientprofile', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drive_axles', to='service.machinedirectory', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engines', to='service.machinedirectory', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_models', to='service.machinedirectory', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintain_units', to='service.servicecompanyprofile', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steered_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steered_axles', to='service.machinedirectory', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmissions', to='service.machinedirectory', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holders', to='service.repairdirectory', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='service.servicecompanyprofile', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='service.repairdirectory', verbose_name='Вид ТО'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='repair_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='methods', to='service.repairdirectory', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='service.servicecompanyprofile', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='service.repairdirectory', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='servicecompanyprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт в системе'),
        ),
    ]
